### ISSUE TITLE
lookup for setuptools in sys.modules is a no-op

### ISSUE THREAD

**Issue by lorencarvalho** [saltstack/salt-pylint#16]
Unless you import setuptools (which does not happen in `setup.py`), 'setuptools' will not be found in `sys.modules`, thus the lookup here:

https://github.com/saltstack/salt-pylint/blob/master/setup.py#L68

will never return `True`. [This commit](https://github.com/saltstack/salt-pylint/commit/0a87ff66b3647ad567cff65b845e67c52db3524d) purports to fix the issue, but it does not.

**Comment by lorencarvalho** [comment]
Annnnnd I was wrong 😆

```lcarvalh-mn1 ~ ❱❱❱ mkdir tmp_py
lcarvalh-mn1 ~ ❱❱❱ cd tmp_py/
lcarvalh-mn1 ~/tmp_py ❱❱❱ vi setup.py
lcarvalh-mn1 ~/tmp_py ❱❱❱ cat setup.py
import sys

print('setuptools' in sys.modules)
lcarvalh-mn1 ~/tmp_py ❱❱❱ python3 -m venv .
lcarvalh-mn1 ~/tmp_py ❱❱❱ . bin/activate
(tmp_py) lcarvalh-mn1 ~/tmp_py ❱❱❱ pip install .
Processing /Users/lcarvalh/tmp_py
    True
```

closing!

**Comment by sgg** [comment]
@sixninetynine this is still problematic to my eyes for few reasons:

1) This only works if used under `pip install`. `pip` [imports `setuptools`](https://github.com/pypa/pip/blob/9.0.1/pip/req/req_install.py#L387) during install. If you try to leverage the `setup.py` directly (e.g. `python setup.py`) then of course it fails because `setuptools` hasn't been imported.

2) The fundamental logic implemented in #14 is circular as you pointed out. It's effectively saying "if this has already been imported, then we can import it." It works due to side-effects of the environment rather than anything explicit.

3) We've tightly coupled the success of our build to an _internal implementation detail_ of `pip` that could change at any point. This arguably makes the process more brittle.

**Comment by lorencarvalho** [comment]
@sgg actually yeah, {1} is a really good point. 

Reopened.

**Comment by s0undt3ch** [comment]
This issue is not valid, do note the environ lookup before checking if setuptools is imported.

Closing. Please reopen if need be.
